### ISSUE TITLE
No ADD primitive?

### ISSUE THREAD

**Issue by DC-Shi** [NVIDIA/hpc-container-maker#149]
`ADD some.tar.gz /data` would extract the tarball to destination, but `COPY` only copy the file, no extraction.

Extracting source code for compile or extract binary files into container would be common usage for docker building from my experience. I hope this primitive can be added into hpccm.

(This might be a docker specific problem.)

**Comment by samcmill** [comment]
Hi @DC-Shi - thanks for your interest in HPCCM.

[Docker advises](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#add-or-copy) using `COPY` instead of `ADD` in nearly all cases.

If you must use `ADD`, consider the `raw` primitive (although if you ever intent to generate Singularity definition files from the same recipe, you need to include a Singularity equivalent).

```
Stage0 += raw(docker='ADD some.tar.gz /data')
```
