### ISSUE TITLE
yum errors with same repo twice

### ISSUE THREAD

**Issue by cliffburdick** [NVIDIA/hpc-container-maker#367]
When installing both nsys and nsight-compute in a centos container, it issues the following command: 

```
RUN rpm --import https://developer.download.nvidia.com/devtools/repos/rhel7/x86_64/nvidia.pub && \
    yum install -y yum-utils && \
    yum-config-manager --add-repo https://developer.download.nvidia.com/devtools/repos/rhel7/x86_64 && \
    yum install -y \
        nsight-systems-cli-2021.1.1 && \
    rm -rf /var/cache/yum/*
# NVIDIA Nsight Compute 2020.2.1
RUN rpm --import https://developer.download.nvidia.com/devtools/repos/rhel7/x86_64/nvidia.pub && \
    yum install -y yum-utils && \
    yum-config-manager --add-repo https://developer.download.nvidia.com/devtools/repos/rhel7/x86_64 && \
    yum install -y \
        nsight-compute-2020.2.1 && \
    rm -rf /var/cache/yum/*
```

This errors out because yum-config-manager does not allow the same repo to be added twice:
```
adding repo from: https://developer.download.nvidia.com/devtools/repos/rhel7/x86_64
Cannot add repo from https://developer.download.nvidia.com/devtools/repos/rhel7/x86_64 as is a duplicate of an existing repo
```

**Comment by samcmill** [comment]
Unfortunately I haven't found an elegant solution to this.

Here's the best I've come up with:
1. Ignore the return status of `yum-config-manager --add-repo`.  This would involve adding a (non-default?) option to the `yum` building block that would use `(yum-config-manager --add-repo https://developer.download.nvidia.com/devtools/repos/rhel7/x86_64 || true)` instead of `yum-config-manager --add-repo https://developer.download.nvidia.com/devtools/repos/rhel7/x86_64`.
2. Remove the repo file at the end of the building block.  This would involve adding a (non-default?) option to the `yum` building block that would run `rm -f /etc/yum.repos.d/developer.download.nvidia.com_devtools_repos_rhel7_x86_64.repo` after installing the packages.
3. Combine the `nsight_systems` and `nsight_compute` building blocks into a single `nsight` building block.  The repo would only need to be added once, with options to individually enable / disable installing Nsight System and Nsight Compute.  However, this would break existing recipes.

Thoughts?

**Comment by cliffburdick** [comment]
@samcmill same. I was hoping there would be an option to ignore a repo if it exists on yum-config-manager, but unfortunately, there's not. 3 sounds like the best option if it didn't break existing recipes, so it's probably a non-starter. There may also be another tool down the line that uses the same repo, and it would break again.  I like the first option as a quick hack since that command shouldn't fail anyways.
