### ISSUE TITLE
NVHPC runtime() doesn't copy files correctly except for files in REDIST/compilers

### ISSUE THREAD

**Issue by dengzeyu** [NVIDIA/hpc-container-maker#494]
I'm using multistage building for an app using NVHPC. runtime() can copy REDIST/compilers/* but the files in other folders (comm_libs, math_libs, and cuda) remained broken symbolic links. I don't want to copy the whole NVHPC devel library. How can I solve this issue?

```python
nvhpc_version = '24.7'
cuda_version = '12.5'
Stage0 += baseimage(image='ubuntu:24.04', _as='devel')
Stage0 += nvhpc(cuda=cuda_version, cuda_multi=False,eula=True, version = nvhpc_version, mpi=True, 
                  redist=['compilers/lib/*',
                   'comm_libs/*', 
                   'math_libs/*', 
                   'cuda/*'])

Stage1 += baseimage(image='ubuntu:24.04')
Stage1 += Stage0.runtime(_from='devel')
```

**Comment by samcmill** [comment]
Please try this:

```
Stage0 += nvhpc(cuda=cuda_version, cuda_multi=False,eula=True, version = nvhpc_version, mpi=True,
                  redist=['compilers/lib/*',
                   'comm_libs/12.5/nccl/lib/*', 
                   'comm_libs/12.5/nvshmem/lib/*', 
                   'math_libs/12.5/targets/x86_64-linux/lib/*',
                   'cuda/12.5/targets/x86_64-linux/lib/*'])
```

Docker's COPY semantics are a little confusing on how it handles subdirectories and symlinks, see https://docs.docker.com/reference/dockerfile/#copy and https://github.com/moby/moby/issues/40449.  It doesn't help that the `REDIST` directory points to locations outside that tree.  

Since you are essentially copying the entire REDIST, an alternative would be to use the runtime container available on NGC, `nvcr.io/nvidia/nvhpc:24.7-runtime-cuda12.5-ubuntu24.04` for your second stage base image.

**Comment by dengzeyu** [comment]
Thanks. I tried to use the runtime image. However, some lib files are missing. I manually copied following files to the runtime image so my code can run now. However, I hope there will be a more elegant way to do this.

/opt/nvidia/hpc_sdk/Linux_x86_64/24.7/compilers/extras/qd/lib/libqdmod.so.0
/opt/nvidia/hpc_sdk/Linux_x86_64/24.7/cuda/12.5/targets/x86_64-linux/lib/libnvJitLink.so*
/opt/nvidia/hpc_sdk/Linux_x86_64/24.7/compilers/lib/libcudaforwrapblas117.so*
/opt/nvidia/hpc_sdk/Linux_x86_64/24.7/compilers/lib/libnvhpcwrapcufft.so*

**Comment by samcmill** [comment]
I'll file a bug with the HPC SDK team about those missing libraries.  Thanks for pointing them out!
